apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-deploy
  labels:
    app: subscription-deploy
spec:
  selector:
    matchLabels:
      app: subscription
  replicas: 2
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: infosys/subscription:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_ADDRESS
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC_NAME
              value: "mail-topic"
            - name: MYSQL_ADDRESS
              value: "jdbc:mysql://mysql:3306/subscriptions"
            - name: MYSQL_ACCOUNT_USERNAME
              value: "root"
            - name: MYSQL_ACCOUNT_PASSWORD
              value: "password"
          imagePullPolicy: Never
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: subscription-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: subscription-deploy
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80