kind: Service
apiVersion: v1
metadata:
  name: subscription-service
spec:
  selector:
    app: subscription
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer